feat: add calculated data documents to PerkinElmer EnVision
Benchling-Open-Source/allotropy pull request #166
Opened 2023-12-01 14:55 UTC by alejandro-salgado

- Calculated data documents to PerkinElmer EnVision

2023-12-01 18:11 UTC, bdworth reviewed
Quick question from a quick review

2023-12-01 18:48 UTC, mdlu requested changes

2023-12-01 18:48 UTC, mdlu commented on src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
> +            msg="Unable to get expected formula for calculated results section",
would you mind changing all the error messages that you've added throughout this PR? I changed the guidelines recently https://github.com/Benchling-Open-Source/allotropy/blob/main/CONTRIBUTING.md#error-messaging (in particular, changing `get` to `find` here and in other places, ending with a period, and maybe printing the `series` as well if you think that would be valuable to an end user)

2023-12-01 20:38 UTC, nathan-stender commented on src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py
> +    plates: PlateList
It seems like we could just store this in `Data` as a list of `Plate`s, we've done this in other parsers.

Have `Plate.create` create a single plate, and then you can make another function called `create_plates` that returns a list of plates.

2023-12-04 21:48 UTC, mdlu approved these changes

2023-12-04 22:06 UTC, merged