Remove deprecated flake8 and mypy vscode settings
Benchling-Open-Source/allotropy pull request #167
Opened 2023-12-01 18:10 UTC by chrisfriedline-benchling

VS Code has deprecated the following settings. Users should install and enable the individual flake8 and mypy extensions instead.

```
2023-12-01 12:54:42.453 [error] Following setting is deprecated: "python.linting.flake8Enabled"
2023-12-01 12:54:42.453 [error] All settings starting with "python.linting." are deprecated and can be removed from settings.
2023-12-01 12:54:42.453 [error] Linting features have been moved to separate linter extensions.
2023-12-01 12:54:42.453 [error] See here for more information: https://code.visualstudio.com/docs/python/linting
2023-12-01 12:54:42.453 [error] Please install "flake8" extension: https://marketplace.visualstudio.com/items?itemName=ms-python.flake8
2023-12-01 12:54:42.453 [error] Following setting is deprecated: "python.linting.mypyEnabled"
2023-12-01 12:54:42.453 [error] All settings starting with "python.linting." are deprecated and can be removed from settings.
2023-12-01 12:54:42.453 [error] Linting features have been moved to separate linter extensions.
2023-12-01 12:54:42.453 [error] See here for more information: https://code.visualstudio.com/docs/python/linting
2023-12-01 12:54:42.453 [error] Please install "mypy" extension: https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker
```

2023-12-01 18:31 UTC, bdworth requested changes
1. It seems like you changed the number of spaces in a tab from 2 to 4, thus changing every line. Was that autogenerated? (I don't use VSCode, so not sure.)
2. This repo doesn't use flake8, just ruff's implementations of flake8 checks. Could you please remove all flake8 content?

2023-12-01 18:48 UTC, chrisfriedline-benchling commented
> 1. It seems like you changed the number of spaces in a tab from 2 to 4, thus changing every line. Was that autogenerated? (I don't use VSCode, so not sure.)
> 2. This repo doesn't use flake8, just ruff's implementations of flake8 checks. Could you please remove all flake8 content?

Yes, this was done automatically by vscode (i.e., the prettier extension). Will do #2.

2023-12-15 21:39 UTC, bdworth commented
I don't use VSCode, so recusing myself.

2024-02-15 16:14 UTC, mdlu approved these changes

2024-04-23 17:20 UTC, nathan-stender approved these changes

2024-04-24 14:43 UTC, nathan-stender approved these changes

2024-04-24 14:43 UTC, merged