Fix: calculated data name in elmer envision
Benchling-Open-Source/allotropy pull request #215
Opened 2023-12-22 18:12 UTC by slopez-b

In the Perkin Elmer Envision Adapter the calculated data name of the calculated data documents was being incorrectly parsed.
- Instead of grabbing the left part of the `formula` column on the `Plate information` block, the adapter was taking the right part.
- Added additional test for the structure class in charge of parsing this property.

2023-12-23 14:54 UTC, nathan-stender requested changes
Change looks good, but I'd like to avoid just re-generating the test files whenever possible. It seems like it should be possible in this case, so requesting you do that instead.

2023-12-23 14:54 UTC, nathan-stender commented on tests/parsers/perkin_elmer_envision/testdata/PE_Envision_fluorescence_example01.json
> +                    "calculated data name": "Calc 1: General",
it seems like you could find/replace "calculated data name" value in the test files and prevent the "measurement identifier" changes, making the test changes clearer, can you do that please?

2024-01-02 20:43 UTC, alejandro-salgado approved these changes

2024-01-03 06:15 UTC, nathan-stender approved these changes

2024-01-03 13:58 UTC, merged