Move random_uuid_str to vendor_parser
Benchling-Open-Source/allotropy pull request #295
Opened 2024-02-15 21:02 UTC by bdworth

2024-02-16 20:52 UTC, slopez-b commented on src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_structure.py
> +    return SoftmaxproParser.random_uuid_str()
@bdworth should this function actually depend on `SoftpaxproParser` implementation of `random_uuid_str`?

What if the parser is deprecated in the future? I personally think parsers should be independent from each other.

2024-02-16 20:54 UTC, slopez-b requested changes

2024-02-16 20:54 UTC, slopez-b commented on src/allotropy/parsers/appbio_quantstudio/appbio_quantstudio_structure.py
> +    return SoftmaxproParser.random_uuid_str()
also applies for `src/allotropy/parsers/perkin_elmer_envision/perkin_elmer_envision_structure.py`

2024-02-19 16:32 UTC, bdworth commented
replaced by #309

2024-02-19 16:32 UTC, closed without merging