Nanodrop data source ids
Benchling-Open-Source/allotropy pull request #300
Opened 2024-02-16 19:02 UTC by bwolfe-benchling

Fix problem where data source IDs were being used that did not refer to any existing measurement ID.

2024-02-16 19:38 UTC, bdworth requested changes
mostly lgtm, but a few small comments

2024-02-16 19:38 UTC, bdworth commented on tests/parsers/thermo_fisher_nanodrop_eight/testdata/Thermo_NanoDrop_Eight_example01.json
> +                            "measurement identifier": "f692658e-62f2-4383-8770-f0d97d2c17df",
Hopefully #296 will merge before this, in which case none of these ids will change anymore!

2024-02-16 19:38 UTC, bdworth commented on src/allotropy/parsers/thermo_fisher_nanodrop_eight/nanodrop_eight_parser.py
> +        if len(data_source_doc_items):
```suggestion
        if data_source_doc_items:
```

2024-02-16 19:38 UTC, bdworth commented on src/allotropy/parsers/thermo_fisher_nanodrop_eight/nanodrop_eight_parser.py
> +                data_source_document=data_source_doc_items
Could you rename `data_source_doc` to `data_source_aggregated_document`? It's a bit confusing to read this as is.

2024-02-16 19:38 UTC, bdworth commented on src/allotropy/parsers/thermo_fisher_nanodrop_eight/nanodrop_eight_parser.py
> +                data_source_document=data_source_doc_items
same comments as above

2024-02-16 19:38 UTC, bdworth commented on tests/parsers/thermo_fisher_nanodrop_eight/thermo_fisher_nanodrop_eight_parser_test.py
> +        assert data_source_id in measurement_ids
If this test fails, we won't get a very helpful error message. Could you add one?

2024-02-20 00:04 UTC, nathan-stender approved these changes

2024-02-22 19:15 UTC, merged