Add Display Names for Vendors
Benchling-Open-Source/allotropy pull request #389
Opened 2024-04-25 19:35 UTC by stephenworlow

Add Display Names for Vendors

2024-04-26 16:09 UTC, LimulusPolyphemus requested changes
@stephenworlow could we change "Biorad Bioplex" to "BioRad BioPlex Manager"? There is another application called "BioRad BioPlex Data Pro" and I want to be sure we're distinguishing between the two.

2024-04-26 17:59 UTC, LimulusPolyphemus requested changes
@stephenworlow one more, could we change:
"AppBio QuantStudio" --> "AppBio QuantStudio RT-PCR"
"Luminex XPonent" --> "Luminex xPONENT"
"Qiacuity DPCR" --> "Qiacuity dPCR"

2024-04-29 18:44 UTC, nathan-stender approved these changes

2024-04-30 13:56 UTC, LimulusPolyphemus approved these changes

2024-04-30 15:45 UTC, closed without merging