support block type starting with non-numeric
Benchling-Open-Source/allotropy pull request #457
Opened 2024-06-07 20:38 UTC by bwolfe-benchling

2024-06-10 14:28 UTC, nathan-stender approved these changes

2024-06-10 14:33 UTC, nathan-stender requested changes
Please add CHANGELOG entry

2024-06-14 19:36 UTC, LimulusPolyphemus commented
@bwolfe-benchling could we be sure to include a 'NaN' is if there is no value found.

2024-08-18 03:45 UTC, nathan-stender approved these changes

2024-08-18 03:47 UTC, nathan-stender commented
Closing this out because it was done here: https://github.com/Benchling-Open-Source/allotropy/pull/466

2024-08-18 03:47 UTC, closed without merging