Add Alphalisa endpoint to Gen5
Benchling-Open-Source/allotropy pull request #468
Opened 2024-06-18 22:07 UTC by dchou-benchling

This PR adds support for alphalisa fluorescence assays for the Gen5 adapter. 

NOTE: This is only expected one "read" in the file

2024-06-19 14:10 UTC, slopez-b requested changes
Just a small request to make an attribute optional. Everything else LGTM.

2024-06-20 17:34 UTC, dchou-benchling commented on src/allotropy/parsers/agilent_gen5/agilent_gen5_structure.py
> +                emission=emissions[idx] if emissions else None,
Good catch! I'm surprised the linter didn't catch this

2024-06-20 19:06 UTC, slopez-b approved these changes

2024-06-20 19:49 UTC, stephenworlow approved these changes

2024-06-20 20:07 UTC, merged