feat: Make all adapters have the asm converter name
Benchling-Open-Source/allotropy pull request #501
Opened 2024-07-10 14:10 UTC by joshua-benchling

Update ASM converter name field to specify the parser name instead of just "allotropy", this is intended to give better granularity on the adapter that did the conversion and not just the library version

2024-07-10 16:02 UTC, nathan-stender requested changes
Whoop! Knocking something off my personal TODO list! Thank you!

A couple requests, but otherwise LGTM

2024-07-10 16:02 UTC, nathan-stender commented on src/allotropy/parsers/vendor_parser.py
> +        return f'{ASM_CONVERTER_NAME}_{self.display_name.replace(" ", "_")}'.lower()
Can we replace `-` with `_` as well?

2024-07-10 16:09 UTC, slopez-b reviewed
LGTM! just a little nit (feel free to ignore)

2024-07-10 16:09 UTC, slopez-b commented on src/allotropy/parsers/biorad_bioplex_manager/biorad_bioplex_manager_parser.py
>                  data_system_document=self._get_data_system_document(
I know this falls outside the scope of this refactor, but it seems unnecessary to have a method that just returns an instance of `DataSystemDocument` with the arguments passed.

Would you mind removing this code redundancy?

2024-07-10 18:07 UTC, nathan-stender commented
@james-leinas sorry - https://github.com/Benchling-Open-Source/allotropy/pull/499 is going to cause a big headache to merge 😓 

But for the most part - you can accept all changes from the incoming PR - which removes a lot of test code - and just add the vendor argument to `validate_contents` in `ParserTest.test_positive_cases` in `tests/to_allotrope_test.py`

2024-07-11 13:50 UTC, nathan-stender approved these changes
🎉

2024-07-11 13:54 UTC, merged