feat: Solution analyzer 2024 09 update schema mapper
Benchling-Open-Source/allotropy pull request #714
Opened 2024-10-10 16:59 UTC by joshua-benchling

Add new schema mapper according to the new Solution Analyzer 2024/09 schema.

2024-10-10 19:30 UTC, james-leinas requested changes

2024-10-10 19:30 UTC, james-leinas commented on src/allotropy/allotrope/schema_mappers/adm/solution_analyzer/rec/_2024/_09/solution_analyzer.py
> +    MANIFEST = "http://purl.allotrope.org/manifests/solution-analyzer/REC/2024/03/solution-analyzer.manifest"
One note to change the manifest version to REC/2024/09

2024-10-11 15:18 UTC, james-leinas approved these changes

2024-10-11 21:52 UTC, nathan-stender approved these changes
Code looks good!

Can you change title to `feat: Add solution-analyzer/rec/2024/09 schema mapper`

2024-10-12 00:21 UTC, merged