Fix: MSD Methodical Mind - Delimiter Error
Benchling-Open-Source/allotropy pull request #795
Opened 2024-11-27 16:38 UTC by joshua-benchling

- Skipped Digital Signature top line

2024-11-27 17:55 UTC, james-leinas requested changes
@joshua-benchling, the `plate well count` field looks to be recorded as "108". Expected value should be 96. 

We should implement the recording based on this in the requirements:
![image](https://github.com/user-attachments/assets/bdf16b87-cd1c-487d-abca-6aa676d29926)

2024-11-27 18:06 UTC, james-leinas requested changes
@joshua-benchling, also looks like the `location identifier` field records the plate row (e.g. "A", "B", "C") only for the first row "A". Rest of the file contains only the plate column. Potentially formatting difference within the _Data_ (Plate Matrix)?

2024-12-02 16:33 UTC, james-leinas approved these changes

2024-12-02 20:12 UTC, nathan-stender approved these changes
Code LGTM - I changed the title - please check to make sure I got it right.  Going forward, please make sure the description of the fix is always a complete sentence that describes the change (remember these become changelog entries!)

2024-12-04 02:05 UTC, merged