feat: Moldev Softmax Pro - add support for spectrum data
Benchling-Open-Source/allotropy pull request #819
Opened 2024-12-12 13:47 UTC by joshua-benchling

- Added support to reading and parsing spectrum data
- Updated plate reader schema mapper to support custom info doc at measurement group level

2024-12-12 15:27 UTC, nathan-stender requested changes

2024-12-12 15:27 UTC, nathan-stender commented on tests/parsers/moldev_softmax_pro/testdata/spectrum_data.txt
> +##BLOCKS= 97
Lets cut down this test file size to 2 or 3 wavelengths, to keep test time down.

2024-12-12 15:27 UTC, nathan-stender commented on tests/parsers/moldev_softmax_pro/to_allotrope_test.py
> -        f"{TESTDATA}/errors/lum_spectrum_columns.txt",
It looks like this file still does not work with our parser.

Please add logic to detect this and raise an error message.

And example could be detecting if the read_type == Spectrum and the measurment type == lum, raising an error saying we don't support lum spectrum format at this time.

2024-12-12 15:30 UTC, nathan-stender commented on src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
> -    @staticmethod
I see why you moved this, but moving it to the `PlateData` class isn't ideal either, as is break encapsulation.

I would suggest either:

1. Keeping 1 `RawPlateData` class, and having `create` do the different logic based on read_type
2. Having a base class `RawPlateData` that is a base class to two subclasses `SpectrumRawPlateData` and something like `EndpointAndKineticRawPlateData`, then keeping common logic (like this function) in the base class

2024-12-13 22:22 UTC, nathan-stender requested changes
One last tiny language change request

Also - please change the parser name to `Molecular Devices SoftMax Pro` in the title

2024-12-13 22:22 UTC, nathan-stender commented on src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
> +            msg = "Spectrum read type is not supported for fluorescence plates."
```suggestion
            msg = "Spectrum read type is not currently supported for fluorescence plates."
```

2024-12-13 22:22 UTC, nathan-stender commented on src/allotropy/parsers/moldev_softmax_pro/softmax_pro_structure.py
> +            msg = "Spectrum read type is not supported for luminescence plates."
```suggestion
            msg = "Spectrum read type is not currently supported for luminescence plates."
```

2024-12-13 22:22 UTC, nathan-stender commented on tests/parsers/moldev_softmax_pro/to_allotrope_test.py
> +        match="Spectrum read type is not supported for luminescence plates.",
```suggestion
        match="Spectrum read type is not currently supported for luminescence plates.",
```

2024-12-16 18:34 UTC, james-leinas approved these changes
ASM output 👍

2024-12-16 19:38 UTC, merged