feat: Bmg Labtech Smart Control - Initial implementation
Benchling-Open-Source/allotropy pull request #831
Opened 2024-12-27 00:16 UTC by joshua-benchling

Added new adapter Bmg Labtech Smart Control

2025-01-06 17:23 UTC, james-leinas requested changes

2025-01-06 17:23 UTC, james-leinas commented on tests/parsers/bmg_labtech_smart_control/testdata/fluroescence_endpoint_example1.json
> +                                    "unit": "pg/mL"
@joshua-benchling, since SMART Control reports the concentration in ng/mL and the Plate Reader schema accepts only pg/mL, we'll need to do a conversion from ng/mL within the adapter.

![image](https://github.com/user-attachments/assets/bba1e087-14f5-467a-a6cb-c6dbbba8ff26)

2025-01-06 17:23 UTC, james-leinas commented on tests/parsers/bmg_labtech_smart_control/testdata/fluroescence_endpoint_example1.json
> +
@joshua-benchling, it looks like the data source identifier's for the `fluorescence` and `Average of all blanks used` features are swapped. The `fluorescence` feature should align to the first measurement document's `measurement identifier`

2025-01-08 18:32 UTC, james-leinas submitted a review, later dismissed
🎉

2025-01-08 21:42 UTC, nathan-stender requested changes

2025-01-08 21:42 UTC, nathan-stender commented on src/allotropy/parsers/bmg_labtech_smart_control/bmg_labtech_smart_control_structure.py
> +def _get_target_temperature(row: SeriesData) -> float | None:
Nit, but I'd just move this logic inside the function, we already do simple 1 or 2 line processing on other fields.

In fact, because "set off" won't parse to a float, and you're just setting to None anyway, you can replace this with just: `row.get(float, TARGET_TEMPERATURE)` and it will work the same.

2025-01-08 21:42 UTC, nathan-stender commented on src/allotropy/parsers/bmg_labtech_smart_control/bmg_labtech_smart_control_structure.py
> +    blank_average = sum(
We should not be manually calculating calculated data values, we should only report what is in the file.

I checked with @james-leinas and he says that this value should be the file

2025-01-09 14:13 UTC, joshua-benchling commented on src/allotropy/parsers/bmg_labtech_smart_control/bmg_labtech_smart_control_parser.py
> +        measurement_groups = create_measurement_groups(reader.header, reader.data)
But this is actually used twice, as an argument for `Data` and an argument for `create_calculated_data_documents`

2025-01-09 14:13 UTC, joshua-benchling commented on src/allotropy/parsers/bmg_labtech_smart_control/bmg_labtech_smart_control_structure.py
> +    def map_measurement_group(row: SeriesData) -> MeasurementGroup:
but I did use a global state outside of the function, which is the `headers`. The thing is that `map_rows` can´t pass additional arguments besides the data and the handler.

2025-01-09 18:53 UTC, james-leinas reviewed
@nathan-stender, asked @joshua-benchling to log a warning rather than fail if we are unable to extract the average of blanks value from the file, since calculated data documents are optional. Will help to debug if issue with extracting the data

2025-01-10 14:13 UTC, nathan-stender requested changes
Thanks for the fixes, and sorry I missed a couple things in my review - one more change!

2025-01-10 14:13 UTC, nathan-stender commented on src/allotropy/parsers/bmg_labtech_smart_control/bmg_labtech_smart_control_parser.py
> +        measurement_groups = create_measurement_groups(reader.header, reader.data)
Oops, I see 👍

2025-01-10 14:13 UTC, nathan-stender commented on src/allotropy/parsers/bmg_labtech_smart_control/bmg_labtech_smart_control_structure.py
> +    def map_measurement_group(row: SeriesData) -> MeasurementGroup:
Ah, I didn't see that you had to use another argument. There actually is a way to do this: functools.partial

You can make:

`create_measurement_group(data: SeriesData, headers: SeriesData)`

and then call

`map_rows(data, partial(create_measurement_group, headers=headers))`

See tecan_magellan_parser for an example!

2025-01-10 21:37 UTC, james-leinas submitted a review, later dismissed

2025-01-17 19:45 UTC, nathan-stender commented on src/allotropy/parsers/bmg_labtech_smart_control/constants.py
> +DISPLAY_NAME = "BMG SMART Control"
```suggestion
DISPLAY_NAME = "BMG Labtech SMART Control"
```
Sorry just noticed this

2025-01-17 19:45 UTC, nathan-stender commented on src/allotropy/parsers/bmg_labtech_smart_control/constants.py
> +DISPLAY_NAME = "BMG SMART Control"
(will need to update auto-generated tables as well)

2025-01-17 21:47 UTC, nathan-stender approved these changes

2025-01-21 15:48 UTC, merged